@pizza-store-sidecar-url=http://localhost:3501
@component-name=pizzastatestore
@order-id=123456789

### Save state
POST {{pizza-store-sidecar-url}}/v1.0/state/{{component-name}}
Content-Type: application/json

[
    {
        "key": "{{order-id}}",
        "value": { "customer": { "name": "fernando", "email": "fernando@email.com" },"items": [ { "type":"vegetarian", "amount": 2 } ], "address": "KubeCon Salt Lake City", "creditCard": "1111-22222-3333-44444", "drink": "Soda", "event": "Sent to kitchen", "orderId" : "{{order-id}}" }
    }
]

### Get state
GET {{pizza-store-sidecar-url}}/v1.0/state/{{component-name}}/{{order-id}}

### Delete state
DELETE  {{pizza-store-sidecar-url}}/v1.0/state/{{component-name}}/{{order-id}}